import { Geist, Geist_Mono, Mona_Sans } from "next/font/google";
import "./globals.css";
import { ComingSoon } from "@/components/coming-soon";

const monaSans = Mona_Sans({
  variable: "--font-mona-sans", 
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${monaSans.variable}  antialiased`}
      >
        <ComingSoon/>
        {/* {children} */}
      </body>
    </html>
  );
}
